# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provider("virtualbox") { |vb| vb.memory = "1536" }
  config.vm.network "forwarded_port", guest: 4601, host: 4601
  config.vm.synced_folder "..", "/home/ubuntu/go/src/github.com/46bit/discovery"
  config.vm.provision "shell", privileged: false, path: "provision.sh"
end
